### ISSUE TITLE
Oppgrader til java 11

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/terms-and-conditions#2]
Det burde vel ikkje vere ein grunn til å ta utgangspunkt i gammal versjon av java 8 når vi skriv ting frå scratch. Det er instant teknisk gjeld. Men så klart, om vi har ein god grunn, er det ok.

_Originally posted by @stigbd in https://github.com/Informasjonsforvaltning/terms-and-conditions/pull/1_

**Comment by NilsOveTen** [comment]
Ble fikset av https://github.com/Informasjonsforvaltning/terms-and-conditions/pull/12
