### ISSUE TITLE
Lag gui i FDK-admin for å opprette ny versjon av vilkårstekst

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/terms-and-conditions#3]
Denne skal gjere POST mot /terms og må følge [semantisk versjonering](https://semver.org/)

**Comment by KjerstiSteien** [comment]
@KurtStian har vi fortsatt behov for dette, etter din mening? Kan være relevant når vi kommer dit at vi skal oppdatere bruksvilkårene.

**Comment by KurtStian** [comment]
@KjerstiSteien Skal ikke bruksvilkårene inn på samarbeidsportalen? I så fall kan denne lukkes.

**Comment by KjerstiSteien** [comment]
Jo, det stemmer. Lukker denne.
